PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE profile(id INTEGER PRIMARY KEY, name varchar(64), templateId varchar(64), profileXml varchar(16384), public BOOLEAN, owner varchar(64) NOT NULL DEFAULT 'NONE');
INSERT INTO "profile" VALUES(1,'CardiacEP Default','nektar-cardiac-electrophysiology','<CardiacElectrophysiology>
    <Physics>
        <Model>
            <Monodomain>
                <Chi>0.2</Chi>
                <Cm>20</Cm>
                <IsotropicConductivity>
                    <Conductivity>1</Conductivity>
                </IsotropicConductivity>
            </Monodomain>
        </Model>
        <CellModel>
            <CellModelType>
                <CourtemancheRamirezNattel98>
                    <CellModelVariant>Original</CellModelVariant>
                </CourtemancheRamirezNattel98>
            </CellModelType>
            <SubSteps>10</SubSteps>
        </CellModel>
    </Physics>
    <ProblemSpecification>
        <GeometryAndBoundaryConditions>
            <Geometry></Geometry>
            <BoundaryCondition>
                <Comment></Comment>
                <u>
                    <Type></Type>
                    <Value></Value>
                    <UserDefinedType></UserDefinedType>
                </u>
            </BoundaryCondition>
        </GeometryAndBoundaryConditions>
        <InitialConditions>
            <Constant>1</Constant>
        </InitialConditions>
        <Stimuli>
            <Stimulus>
                <StimulusType>
                    <StimulusPoint>
                        <p_strength>1</p_strength>
                    </StimulusPoint>
                </StimulusType>
                <Protocol>
                    <ProtocolS1>
                        <Start>1</Start>
                        <Duration>1</Duration>
                        <S1CycleLength>1</S1CycleLength>
                        <Num_S1>1</Num_S1>
                    </ProtocolS1>
                </Protocol>
            </Stimulus>
        </Stimuli>
        <Expansion>
            <PolynomialOrder>4</PolynomialOrder>
            <BasisType>MODIFIED</BasisType>
        </Expansion>
        <FinalTime>100</FinalTime>
        <TimeStep>1</TimeStep>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>ContinuousGalerkin</Projection>
        <TimeIntegration>
            <TimeIntegrationMethod>DIRKOrder1</TimeIntegrationMethod>
            <DiffusionAdvancement>Implicit</DiffusionAdvancement>
        </TimeIntegration>
        <MatrixInversion>
            <Direct>
                <SubStructuring>Full</SubStructuring>
            </Direct>
        </MatrixInversion>
        <GlobalOptimizationParameters>
            <BackwardTransform>
                <GlobalMatrixEvaluation></GlobalMatrixEvaluation>
            </BackwardTransform>
            <InnerProductWRTBase>
                <GlobalMatrixEvaluation></GlobalMatrixEvaluation>
            </InnerProductWRTBase>
            <MassMatrixOp>
                <GlobalMatrixEvaluation></GlobalMatrixEvaluation>
            </MassMatrixOp>
            <HelmholtzMatrixOp>
                <GlobalMatrixEvaluation></GlobalMatrixEvaluation>
            </HelmholtzMatrixOp>
        </GlobalOptimizationParameters>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>40</IO_CheckSteps>
        <IO_InfoSteps>20</IO_InfoSteps>
    </Admin>
</CardiacElectrophysiology>',1,'NONE');
INSERT INTO "profile" VALUES(5,'CardiacEP Complete New','nektar-cardiac-electrophysiology','<?xml version="1.0" encoding="UTF-8"?>
<CardiacElectrophysiology>
    <Physics>
        <Model>
            <Monodomain>
                <Chi>0.2</Chi>
                <Cm>20</Cm>
                <IsotropicConductivity>
                    <Conductivity>1</Conductivity>
                </IsotropicConductivity>
            </Monodomain>
        </Model>
        <CellModel>
            <CellModelType>
                <CourtemancheRamirezNattel98>
                    <CellModelVariant>Original</CellModelVariant>
                </CourtemancheRamirezNattel98>
            </CellModelType>
            <SubSteps>10</SubSteps>
        </CellModel>
    </Physics>
    <ProblemSpecification>
        <GeometryAndBoundaryConditions>
            <Geometry>CardiacGeometry.xml</Geometry>
            <BoundaryCondition>
                <Comment>NotProvided</Comment>
                <u>
                    <Type>NotProvided</Type>
                    <Value>NotProvided</Value>
                    <UserDefinedType>NotProvided</UserDefinedType>
                </u>
            </BoundaryCondition>
            <BoundaryCondition>
                <Comment>NotProvided</Comment>
                <u>
                    <Type>NotProvided</Type>
                    <Value>NotProvided</Value>
                    <UserDefinedType>NotProvided</UserDefinedType>
                </u>
            </BoundaryCondition>
            <BoundaryCondition>
                <Comment>NotProvided</Comment>
                <u>
                    <Type>NotProvided</Type>
                    <Value>NotProvided</Value>
                    <UserDefinedType>NotProvided</UserDefinedType>
                </u>
            </BoundaryCondition>
        </GeometryAndBoundaryConditions>
        <InitialConditions>
            <Constant>1</Constant>
        </InitialConditions>
        <Stimuli>
            <Stimulus>
                <StimulusType>
                    <StimulusPoint>
                        <p_strength>1</p_strength>
                    </StimulusPoint>
                </StimulusType>
                <Protocol>
                    <ProtocolS1>
                        <Start>1</Start>
                        <Duration>1</Duration>
                        <S1CycleLength>1</S1CycleLength>
                        <Num_S1>1</Num_S1>
                    </ProtocolS1>
                </Protocol>
            </Stimulus>
        </Stimuli>
        <Expansion>
            <PolynomialOrder>4</PolynomialOrder>
            <BasisType>MODIFIED</BasisType>
        </Expansion>
        <FinalTime>100</FinalTime>
        <TimeStep>1</TimeStep>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>ContinuousGalerkin</Projection>
        <TimeIntegration>
            <TimeIntegrationMethod>IMEXOrder1</TimeIntegrationMethod>
            <DiffusionAdvancement>Implicit</DiffusionAdvancement>
        </TimeIntegration>
        <MatrixInversion>
            <Direct>
                <SubStructuring>Full</SubStructuring>
            </Direct>
        </MatrixInversion>
        <GlobalOptimizationParameters>
            <BackwardTransform>
                <GlobalMatrixEvaluation></GlobalMatrixEvaluation>
            </BackwardTransform>
            <InnerProductWRTBase>
                <GlobalMatrixEvaluation></GlobalMatrixEvaluation>
            </InnerProductWRTBase>
            <MassMatrixOp>
                <GlobalMatrixEvaluation></GlobalMatrixEvaluation>
            </MassMatrixOp>
            <HelmholtzMatrixOp>
                <GlobalMatrixEvaluation></GlobalMatrixEvaluation>
            </HelmholtzMatrixOp>
        </GlobalOptimizationParameters>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>40</IO_CheckSteps>
        <IO_InfoSteps>20</IO_InfoSteps>
    </Admin>
</CardiacElectrophysiology>
',0,'jhc02');
INSERT INTO "profile" VALUES(7,'CardiacEP - No ProblemSpec','nektar-cardiac-electrophysiology-bc','<?xml version="1.0" encoding="UTF-8"?>
<CardiacElectrophysiology>
    <Physics>
        <Model>
            <Monodomain>
                <Chi>140</Chi>
                <Cm>0.01</Cm>
                <IsotropicConductivity>
                    <Intensity>
                        <Intensity>0.13341</Intensity>
                        <d_min>750</d_min>
                        <d_max>1250</d_max>
                    </Intensity>
                </IsotropicConductivity>
            </Monodomain>
        </Model>
        <CellModel>
            <CellModelType>
                <CourtemancheRamirezNattel98>
                    <CellModelVariant>Original</CellModelVariant>
                </CourtemancheRamirezNattel98>
            </CellModelType>
            <SubSteps>4</SubSteps>
        </CellModel>
    </Physics>
    <ProblemSpecification>
        <Geometry></Geometry>
        <BoundaryDetails>
        </BoundaryDetails>
        <InitialConditions>
        </InitialConditions>
        <Stimuli>
        </Stimuli>
        <Expansion>
            <PolynomialOrder></PolynomialOrder>
            <BasisType>Select from list</BasisType>
        </Expansion>
        <FinalTime></FinalTime>
        <TimeStep></TimeStep>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>ContinuousGalerkin</Projection>
        <TimeIntegration>
            <TimeIntegrationMethod>IMEXOrder1</TimeIntegrationMethod>
            <DiffusionAdvancement>Implicit</DiffusionAdvancement>
        </TimeIntegration>
        <GlobalSysSolution>
            <MatrixInversion>
                <Field>u</Field>
                <InversionType>
                    <Iterative>
                        <SubStructuring>StaticCondensation</SubStructuring>
                        <Preconditioner>LowEnergy</Preconditioner>
                        <SuccessiveRHS>0</SuccessiveRHS>
                        <IterativeSolverTolerance>1e-05</IterativeSolverTolerance>
                    </Iterative>
                </InversionType>
            </MatrixInversion>
        </GlobalSysSolution>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>100</IO_CheckSteps>
        <IO_InfoSteps>10</IO_InfoSteps>
    </Admin>
</CardiacElectrophysiology>
',1,'jhc02');
INSERT INTO "profile" VALUES(8,'CardiacEP - All inc. ProblemSpec without Geometry','nektar-cardiac-electrophysiology-bc','<?xml version="1.0" encoding="UTF-8"?>
<CardiacElectrophysiology>
    <Physics>
        <Model>
            <Monodomain>
                <Chi>140</Chi>
                <Cm>0.01</Cm>
                <IsotropicConductivity>
                    <Intensity>
                        <Intensity>0.13341</Intensity>
                        <d_min>750</d_min>
                        <d_max>1250</d_max>
                        <o_min>0.001</o_min>
                        <o_max>0.13341</o_max>
                    </Intensity>
                </IsotropicConductivity>
            </Monodomain>
        </Model>
        <CellModel>
            <CellModelType>
                <CourtemancheRamirezNattel98>
                    <CellModelVariant>Original</CellModelVariant>
                </CourtemancheRamirezNattel98>
            </CellModelType>
            <SubSteps>4</SubSteps>
        </CellModel>
    </Physics>
    <ProblemSpecification>
        <Geometry></Geometry>
        <BoundaryDetails>
        </BoundaryDetails>
        <InitialConditions>
            <Variable>
                <VariableName>u</VariableName>
                <Type>
                    <Expression>-81</Expression>
                </Type>
            </Variable>
        </InitialConditions>
        <Stimuli>
            <Stimulus>
                <StimulusType>
                    <StimulusCircle>
                        <p_strength>50.0</p_strength>
                        <p_x1>-10.9</p_x1>
                        <p_y1>8.52</p_y1>
                        <p_z1>33.9</p_z1>
                        <p_r1>3.0</p_r1>
                        <p_is>1.0</p_is>
                    </StimulusCircle>
                </StimulusType>
                <Protocol>
                    <ProtocolSingle>
                        <Start>0.0</Start>
                        <Duration>2.0</Duration>
                    </ProtocolSingle>
                </Protocol>
            </Stimulus>
        </Stimuli>
        <Expansion>
            <PolynomialOrder>3</PolynomialOrder>
            <BasisType>MODIFIED</BasisType>
        </Expansion>
        <FinalTime>50</FinalTime>
        <TimeStep>0.02</TimeStep>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>ContinuousGalerkin</Projection>
        <TimeIntegration>
            <TimeIntegrationMethod>IMEXOrder1</TimeIntegrationMethod>
            <DiffusionAdvancement>Implicit</DiffusionAdvancement>
        </TimeIntegration>
        <GlobalSysSolution>
            <MatrixInversion>
                <Field>u</Field>
                <InversionType>
                    <Iterative>
                        <SubStructuring>StaticCondensation</SubStructuring>
                        <Preconditioner>LowEnergy</Preconditioner>
                        <SuccessiveRHS>0</SuccessiveRHS>
                        <IterativeSolverTolerance>1e-05</IterativeSolverTolerance>
                    </Iterative>
                </InversionType>
            </MatrixInversion>
        </GlobalSysSolution>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>100</IO_CheckSteps>
        <IO_InfoSteps>10</IO_InfoSteps>
    </Admin>
</CardiacElectrophysiology>
',1,'jhc02');
INSERT INTO "profile" VALUES(10,'Cardiac EP Complete','nektar-cardiac-electrophysiology','<?xml version="1.0" encoding="UTF-8"?>
<CardiacElectrophysiology>
    <Physics>
        <Model>
            <Monodomain>
                <Chi>0.2</Chi>
                <Cm>20</Cm>
                <IsotropicConductivity>
                    <Conductivity>1</Conductivity>
                </IsotropicConductivity>
            </Monodomain>
        </Model>
        <CellModel>
            <CellModelType>
                <CourtemancheRamirezNattel98>
                    <CellModelVariant>Original</CellModelVariant>
                </CourtemancheRamirezNattel98>
            </CellModelType>
            <SubSteps>10</SubSteps>
        </CellModel>
    </Physics>
    <ProblemSpecification>
        <GeometryAndBoundaryConditions>
            <Geometry>CardiacGeometry.xml</Geometry>
            <BoundaryCondition>
                <Comment>NotProvided</Comment>
                <u>
                    <Type>NotProvided</Type>
                    <Value>NotProvided</Value>
                    <UserDefinedType>NotProvided</UserDefinedType>
                </u>
            </BoundaryCondition>
        </GeometryAndBoundaryConditions>
        <InitialConditions>
            <Constant>1</Constant>
        </InitialConditions>
        <Stimuli>
            <Stimulus>
                <StimulusType>
                    <StimulusPoint>
                        <p_strength>1</p_strength>
                    </StimulusPoint>
                </StimulusType>
                <Protocol>
                    <ProtocolS1>
                        <Start>1</Start>
                        <Duration>1</Duration>
                        <S1CycleLength>1</S1CycleLength>
                        <Num_S1>1</Num_S1>
                    </ProtocolS1>
                </Protocol>
            </Stimulus>
        </Stimuli>
        <Expansion>
            <PolynomialOrder>4</PolynomialOrder>
            <BasisType>MODIFIED</BasisType>
        </Expansion>
        <FinalTime>100</FinalTime>
        <TimeStep>1</TimeStep>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>ContinuousGalerkin</Projection>
        <TimeIntegration>
            <TimeIntegrationMethod>DIRKOrder1</TimeIntegrationMethod>
            <DiffusionAdvancement>Implicit</DiffusionAdvancement>
        </TimeIntegration>
        <GlobalSysSolution>
            <MatrixInversion>
                <Field>u</Field>
                <InversionType>
                    <Iterative>
                        <SubStructuring>StaticCondensation</SubStructuring>
                        <Preconditioner>LowEnergy</Preconditioner>
                        <SuccessiveRHS>0</SuccessiveRHS>
                        <IterativeSolverTolerance>1e-05</IterativeSolverTolerance>
                    </Iterative>
                </InversionType>
            </MatrixInversion>
        </GlobalSysSolution>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>40</IO_CheckSteps>
        <IO_InfoSteps>20</IO_InfoSteps>
    </Admin>
</CardiacElectrophysiology>
',0,'jhc02');
INSERT INTO "profile" VALUES(11,'Incompressible NS Complete without Geometry','incompressiblenavierstokes-xml','<?xml version="1.0" encoding="UTF-8"?>
<IncompressibleNavierStokes>
    <Physics>
        <KinematicViscosity>0.01</KinematicViscosity>
    </Physics>
    <ProblemSpecification>
        <Geometry></Geometry>
        <BoundaryDetails>
        </BoundaryDetails>
        <SolutionMethod>VelocityCorrectionScheme</SolutionMethod>
        <AdvectionForm>Convective</AdvectionForm>
        <InitialConditions>
            <Variable>
                <VariableName>u</VariableName>
                <Type>
                    <Expression>1</Expression>
                </Type>
            </Variable>
            <Variable>
                <VariableName>v</VariableName>
                <Type>
                    <Expression>0</Expression>
                </Type>
            </Variable>
            <Variable>
                <VariableName>p</VariableName>
                <Type>
                    <Expression>0</Expression>
                </Type>
            </Variable>
        </InitialConditions>
        <Expansion>
            <PolynomialOrder>4</PolynomialOrder>
            <BasisType>MODIFIED</BasisType>
        </Expansion>
        <FinalTime>20</FinalTime>
        <TimeStep>0.01</TimeStep>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>ContinuousGalerkin</Projection>
        <TimeIntegration>
            <TimeIntegrationMethod>IMEXOrder1</TimeIntegrationMethod>
            <DiffusionAdvancement>Implicit</DiffusionAdvancement>
        </TimeIntegration>
        <GlobalSysSolution>
            <MatrixInversion>
                <Field>u</Field>
                <InversionType>
                    <Iterative>
                        <SubStructuring>StaticCondensation</SubStructuring>
                        <Preconditioner>LowEnergy</Preconditioner>
                        <SuccessiveRHS>0</SuccessiveRHS>
                        <IterativeSolverTolerance>1e-05</IterativeSolverTolerance>
                    </Iterative>
                </InversionType>
            </MatrixInversion>
            <MatrixInversion>
                <Field>v</Field>
                <InversionType>
                    <Iterative>
                        <SubStructuring>StaticCondensation</SubStructuring>
                        <Preconditioner>Diagonal</Preconditioner>
                        <SuccessiveRHS>0</SuccessiveRHS>
                        <IterativeSolverTolerance>1e-05</IterativeSolverTolerance>
                    </Iterative>
                </InversionType>
            </MatrixInversion>
            <MatrixInversion>
                <Field>p</Field>
                <InversionType>
                    <Iterative>
                        <SubStructuring>StaticCondensation</SubStructuring>
                        <Preconditioner>LowEnergy</Preconditioner>
                        <SuccessiveRHS>0</SuccessiveRHS>
                        <IterativeSolverTolerance>1e-05</IterativeSolverTolerance>
                    </Iterative>
                </InversionType>
            </MatrixInversion>
        </GlobalSysSolution>
        <SpectralhpDealiasing>Off</SpectralhpDealiasing>
        <WeightPartitions>Uniform</WeightPartitions>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>50</IO_CheckSteps>
        <IO_InfoSteps>10</IO_InfoSteps>
    </Admin>
</IncompressibleNavierStokes>
',0,'jhc02');
INSERT INTO "profile" VALUES(12,'Incompressible NS With Updated Boundary Conditions','incompressiblenavierstokes-xml','<?xml version="1.0" encoding="UTF-8"?>
<IncompressibleNavierStokes>
    <Physics>
        <KinematicViscosity>0.01</KinematicViscosity>
    </Physics>
    <ProblemSpecification>
        <Geometry></Geometry>
        <BoundaryDetails>
            <BoundaryCondition>
                <BoundaryConditionName>Wall</BoundaryConditionName>
                <Variable>
                    <VariableName>u</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                </Variable>
                <Variable>
                    <VariableName>v</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                </Variable>
                <Variable>
                    <VariableName>p</VariableName>
                    <ConditionType>Neumann (N)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                    <UserDefinedType>HighOrderPressure - INS Only</UserDefinedType>
                </Variable>
            </BoundaryCondition>
            <BoundaryCondition>
                <BoundaryConditionName>Far Field</BoundaryConditionName>
                <Variable>
                    <VariableName>u</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>1</Expression>
                    </ConditionValue>
                </Variable>
                <Variable>
                    <VariableName>v</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                </Variable>
                <Variable>
                    <VariableName>p</VariableName>
                    <ConditionType>Neumann (N)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                    <UserDefinedType>HighOrderPressure - INS Only</UserDefinedType>
                </Variable>
            </BoundaryCondition>
            <BoundaryCondition>
                <BoundaryConditionName>Outlet</BoundaryConditionName>
                <Variable>
                    <VariableName>u</VariableName>
                    <ConditionType>Neumann (N)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                </Variable>
                <Variable>
                    <VariableName>v</VariableName>
                    <ConditionType>Neumann (N)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                </Variable>
                <Variable>
                    <VariableName>d</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                </Variable>
            </BoundaryCondition>
        </BoundaryDetails>
        <SolutionMethod>VelocityCorrectionScheme</SolutionMethod>
        <AdvectionForm>Convective</AdvectionForm>
        <InitialConditions>
            <Variable>
                <VariableName>u</VariableName>
                <Type>
                    <Expression>1</Expression>
                </Type>
            </Variable>
            <Variable>
                <VariableName>v</VariableName>
                <Type>
                    <Expression>0</Expression>
                </Type>
            </Variable>
            <Variable>
                <VariableName>p</VariableName>
                <Type>
                    <Expression>0</Expression>
                </Type>
            </Variable>
        </InitialConditions>
        <Expansion>
            <PolynomialOrder>4</PolynomialOrder>
            <BasisType>MODIFIED</BasisType>
        </Expansion>
        <FinalTime>20</FinalTime>
        <TimeStep>0.01</TimeStep>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>ContinuousGalerkin</Projection>
        <TimeIntegration>
            <TimeIntegrationMethod>IMEXOrder1</TimeIntegrationMethod>
            <DiffusionAdvancement>Implicit</DiffusionAdvancement>
        </TimeIntegration>
        <SpectralhpDealiasing>Off</SpectralhpDealiasing>
        <WeightPartitions>Uniform</WeightPartitions>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>50</IO_CheckSteps>
        <IO_InfoSteps>10</IO_InfoSteps>
    </Admin>
</IncompressibleNavierStokes>
',1,'jhc02');
INSERT INTO "profile" VALUES(14,'ADR profile with new style boundary conditions','advectiondiffusion-new','<?xml version="1.0" encoding="UTF-8"?>
<AdvectionDiffusionReaction>
    <ProblemSpecification>
        <EquationType>
            <UnsteadyAdvection>
                <ForcingFunction>NONE</ForcingFunction>
                <InitialConditions>sin(k*x)*cos(k*y)</InitialConditions>
                <Velocity>
                    <VelocityX>advx</VelocityX>
                    <VelocityY>advy</VelocityY>
                    <VelocityZ>NONE</VelocityZ>
                </Velocity>
                <SimulationTimeParams>
                    <FinalTime>1.0</FinalTime>
                    <TimeStep>0.001</TimeStep>
                </SimulationTimeParams>
                <Variables>
                    <k>2*PI</k>
                </Variables>
            </UnsteadyAdvection>
        </EquationType>
        <Geometry></Geometry>
        <BoundaryDetails>
            <BoundaryCondition>
                <BoundaryConditionName>BC1</BoundaryConditionName>
                <Variable>
                    <VariableName>u</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>sin(k*(x-advx*t))*cos(k*(y-advy*t))</Expression>
                    </ConditionValue>
                    <UserDefinedType>TimeDependent</UserDefinedType>
                </Variable>
            </BoundaryCondition>
            <BoundaryCondition>
                <BoundaryConditionName>BC2</BoundaryConditionName>
                <Variable>
                    <VariableName>u</VariableName>
                    <ConditionType>Periodic (P)</ConditionType>
                    <ConditionValue>
                        <Expression>[3]</Expression>
                    </ConditionValue>
                </Variable>
            </BoundaryCondition>
            <BoundaryCondition>
                <BoundaryConditionName>BC3</BoundaryConditionName>
                <Variable>
                    <VariableName>u</VariableName>
                    <ConditionType>Periodic (P)</ConditionType>
                    <ConditionValue>
                        <Expression>[1]</Expression>
                    </ConditionValue>
                </Variable>
            </BoundaryCondition>
        </BoundaryDetails>
        <Expansion>
            <PolynomialOrder>4</PolynomialOrder>
            <BasisType>MODIFIED</BasisType>
        </Expansion>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>
            <DiscontinuousGalerkin>
                <DiffusionType>Not Provided</DiffusionType>
            </DiscontinuousGalerkin>
        </Projection>
        <AdvectionType>WeakDG</AdvectionType>
        <UpwindType>Upwind</UpwindType>
        <TimeIntegration>
            <TimeIntegrationMethod>ClassicalRungeKutta4</TimeIntegrationMethod>
            <DiffusionAdvancement>NotProvided</DiffusionAdvancement>
        </TimeIntegration>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>100</IO_CheckSteps>
        <IO_InfoSteps>100</IO_InfoSteps>
    </Admin>
</AdvectionDiffusionReaction>
',1,'jhc02');
INSERT INTO "profile" VALUES(15,'IsentropicVortex1 example - with new boundary conditions','compressibleflowsolver-xml','<?xml version="1.0" encoding="UTF-8"?>
<CompressibleFlowSolver>
    <Physics>
        <EquationSystem>
            <EulerCFE>
                <AdvectionType>NotSpecified</AdvectionType>
            </EulerCFE>
        </EquationSystem>
        <Gamma>1.4</Gamma>
        <GasConstant>10000000000</GasConstant>
        <AngleOfAttack>0</AngleOfAttack>
        <rhoInf>10000000000</rhoInf>
        <pInf>10000000000</pInf>
        <MachInf>0</MachInf>
    </Physics>
    <ProblemSpecification>
        <Geometry></Geometry>
        <BoundaryDetails>
            <BoundaryCondition>
                <BoundaryConditionName>BC1</BoundaryConditionName>
                <Variable>
                    <VariableName>rho</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                    <UserDefinedType>IsentropicVortex - CFS Only</UserDefinedType>
                </Variable>
                <Variable>
                    <VariableName>rhou</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                    <UserDefinedType>IsentropicVortex - CFS Only</UserDefinedType>
                </Variable>
                <Variable>
                    <VariableName>rhov</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                    <UserDefinedType>IsentropicVortex - CFS Only</UserDefinedType>
                </Variable>
                <Variable>
                    <VariableName>E</VariableName>
                    <ConditionType>Dirichlet (D)</ConditionType>
                    <ConditionValue>
                        <Expression>0</Expression>
                    </ConditionValue>
                    <UserDefinedType>IsentropicVortex - CFS Only</UserDefinedType>
                </Variable>
            </BoundaryCondition>
        </BoundaryDetails>
        <InitialConditions>
            <Problem2D>
                <rho>0</rho>
                <rhou>0</rhou>
                <rhov>0</rhov>
                <E>0</E>
            </Problem2D>
        </InitialConditions>
        <Expansion>
            <PolynomialOrder>2</PolynomialOrder>
            <BasisType>MODIFIED</BasisType>
        </Expansion>
        <FinalTime>0.38</FinalTime>
        <TimeStep>
            <Constant>0.00001</Constant>
        </TimeStep>
        <RiemannSolver>ExactToro</RiemannSolver>
    </ProblemSpecification>
    <NumericalAlgorithm>
        <Projection>DiscontinuousGalerkin</Projection>
        <TimeIntegration>
            <TimeIntegrationMethod>ClassicalRungeKutta4</TimeIntegrationMethod>
            <DiffusionAdvancement>NotProvided</DiffusionAdvancement>
        </TimeIntegration>
    </NumericalAlgorithm>
    <Admin>
        <IO_CheckSteps>10000</IO_CheckSteps>
        <IO_InfoSteps>100</IO_InfoSteps>
    </Admin>
</CompressibleFlowSolver>
',1,'jhc02');
COMMIT;
